### PR TITLE
Implemented DFS in python

### LINKED ISSUE #155: DFS in python
DFS in python should be implemented

### PR DESCRIPTION
**Pull request by s-ayush2903**
Fixes #155 
Added dfs in python and used hardcoded data/case

### CODE REVIEW

**Review by YuvrajSHAD — APPROVED** [review]

**Review by AdarshSR28 — APPROVED** [review]
Well done

**Comment by YuvrajSHAD** [comment]
Please Add ' hacktoberfest-accepted ' Label. Please!!!



On Oct 5, 2020 at 23:03, Adarsh Srivastav <notifications@github.com> wrote:

*@AdarshSR28* approved this pull request.

Well done

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/hacktoberfest2k20/DataStructures-and-Algorithms/pull/156#pullrequestreview-502273613>,
or unsubscribe

**Comment by s-ayush2903** [comment]
@YuvrajSHAD Not needed, it requires only approval or merge. That label isn't necessary

**Comment by YuvrajSHAD** [comment]
Ok


On Oct 5, 2020 at 23:09, Ayush Shrivastava <notifications@github.com>
wrote:

@YuvrajSHAD <https://github.com/YuvrajSHAD> Not needed, it requires only
approval or merge. That label isn't necessary

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hacktoberfest2k20/DataStructures-and-Algorithms/pull/156#issuecomment-703782116>,
or unsubscribe

**Pull request merged**
