### PR TITLE
Bucket Sort Algorithm in C++

### LINKED ISSUE #62: Bucket Sort Algorithm in C++
Sorting an array of numbers using Bucket Sort technique.

### PR DESCRIPTION
**Pull request by Akshat05-tech**
A comparison sort algorithm that operates on elements by dividing them into different buckets and then sorting these buckets.

Fixes #62

### CODE REVIEW

**Review by AdarshSR28 — COMMENTED** [review]
Add time complexity and Name of the Algorithm as a comment in the code at the top!

**Comment by Akshat05-tech** [comment]
@AdarshSR28 I had already written the complexity at the top of the file and the readme.md file says the same. The name of algorithm is written on the top of every heading even in this pr title!!

**Comment by s-ayush2903** [comment]
Resolved, approving

**Review by s-ayush2903 — APPROVED** [review]
LGTM :+1:

**Review by s-ayush2903 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
