### PR TITLE
added height of binary tree cpp

### PR DESCRIPTION
**Pull request by abhi211199**
The code is used to calculate the height of a binary tree.
It is implemented in C++.
For more information about the working of the code, please visit https://www.geeksforgeeks.org/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/

### CODE REVIEW

**Review by AdarshSR28 — APPROVED** [review]
Well done!

**Review by AdarshSR28 — COMMENTED** [review]
Please add a brief description =D

**Comment by abhi211199** [comment]
The code is used to calculate the height of a binary tree.
It is implemented in C++.
For more information about the working of the code, please visit https://www.geeksforgeeks.org/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/

**Comment by AdarshSR28** [comment]
Yep, it has to be added in the description box.
I have done it for you now, make sure of it next time!
Keep contributing!

**Pull request merged**
