### PR TITLE
feat: Added Linear Search in CPP

### LINKED ISSUE #2: Linear search
As linear search is basic algorithm and not present in the repo , it should be added

### PR DESCRIPTION
**Pull request by apoorvadwivedi670**
Linear search algorithm
Fixed #2

### CODE REVIEW

**Comment by s-ayush2903** [comment]
@apoorvadwivedi670 Thanks for your contributions!
In the future PRs can you please title your PRs as I edited yours, a few secs back, it would be very nice of you!

**Comment by apoorvadwivedi670** [comment]
@s-ayush2903 Thanks! 
Sure , I will do as suggested .

**Review by Akshat05-tech — APPROVED** [review]
Thanks for your contribution. Hope to see you contributing further!!

**Review by mayank64ce — COMMENTED** [review]
Cool! Everything seems to be working as expected. Hope to see you contributing further.

**Review by s-ayush2903 — APPROVED** [review]
LGTM

**Pull request merged**
