### PR TITLE
Kadane's algorithm in C++

### LINKED ISSUE #41: Kadane's Algorithm in C
A C++ program to find the largest sum contiguous subarray from an array of integers

### PR DESCRIPTION
**Pull request by Akshat05-tech**
Maximum sum Contiguous Subarray

Fixes #41

### CODE REVIEW

**Review by apoorvadwivedi670 — COMMENTED** [review]
nice work !

**Review by AdarshSR28 — APPROVED** [review]
Great Job @Akshat05-tech !

**Review by mayank64ce — CHANGES_REQUESTED** [review]
Please Mention name of algorithm and complexity as a comment at the top.

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]
Can you please add the time complexities of the algorithms in the files you added(at the top of file)

**Review by mayank64ce — APPROVED** [review]
Cool now! Great job.

**Comment by Akshat05-tech** [comment]
@mayank64ce @s-ayush2903 All changes requested are done.Thanks for pointing it out!!

**Review by s-ayush2903 — APPROVED** [review]
Thanks for considering the requested changes

**Comment by s-ayush2903** [comment]
Merging :tada:

**Pull request merged**
