### PR TITLE
Number of island in binary matrix

### PR DESCRIPTION
**Pull request by ShristiAgrawal**
Number of island in binary matrix using dfs.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
@ShristiAgrawal Why a close?

**Comment by ShristiAgrawal** [comment]
> @ShristiAgrawal Why a close?

Maybe some checks failed.

**Comment by ShristiAgrawal** [comment]
Reopened it.

**Comment by s-ayush2903** [comment]
Don't worry about checks, they ain't the issue, its some ci failure which has nothing to do with PRs(as of now).
Coming to the point, if you want this PR to be considered for merging then please follow the following:
* Please adhere to our [Contribution Guidelines](https://github.com/hacktoberfest2k20/DataStructures-and-Algorithms#datastructures-and-algorithms), as I can find some violations in this PR.

**Pull request closed without merging**
