### PR TITLE
Create char_frequency_count.cpp

### PR DESCRIPTION
**Pull request by sandesh-3112**
this algo count the frequency of the characters

Fixes #

### CODE REVIEW

**Comment by sandesh-3112** [comment]
please add this Pr under hacktoberfest tag

**Comment by s-ayush2903** [comment]
@sandesh-3112 you've added two files which do exactly same thing. Please remove one.

**Comment by sandesh-3112** [comment]
i removed one file now please merge this PR under hacktoberfest tag

**Comment by s-ayush2903** [comment]
Thanks, one more thing, you should update this branch with `master` upon doing so the CI checks will pass and it'll become mergeable

**Comment by sandesh-3112** [comment]
how to do that ?

**Comment by sandesh-3112** [comment]
now it is fine

**Comment by sandesh-3112** [comment]
i sync my current repo with master branch

**Comment by s-ayush2903** [comment]
Right click on the directory where you've cloned this repo and select `open gitbash here`. Now run following in sequence:
1. `git remote -v`
2. note the name in front of `https://github.com/hacktoberfest2k20/DataStructures-and-Algorithms/` url(let's say it is `upstream`)
3. `git pull upstream master`
4. `git push origin master`

This will do the needed

**Review by s-ayush2903 — APPROVED** [review]
Thanks for contribution.

**Comment by sandesh-3112** [comment]
why this repo is excluded from hacktoberfest 2022

**Comment by ItzLevvie** [comment]
There is a commitment — which is a **_compulsary_** requirement — for contributors & maintainers to follow a set of guidelines which is listed [here](https://hacktoberfest.com/participation/).

This repository does not fall into the guidelines that were initially set by DigitalOcean. More specifically, this statement: "**_PR/MRs should be useful to maintainers. Repos that encourage simplistic PR/MRs (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest._**"

^ If you would like me to be even more specific - it's these 3 words: **_arbitrarily curating content_**

This repository was created for the sole purpose of allowing people to contribute pull requests (PRs) with no real purpose other than to be in the "minimum 4 pull requests (PRs)" window to be eligible for a T-Shirt from DigitalOcean.

This 1 week (7 days) of waiting time was implemented so that DigitalOcean can review more than 500K pull requests to ensure that each pull request (PR) meets the guidelines set. Lots of human moderators were chosen by DigitalOcean to take care of this.

If a particular repository was never reported to DigitalOcean where the sole purpose was to defeat the system - it's always — 50% to 75% — possible for your pull requests (PRs) to be flagged and have it **_not_** counted towards your contributions for Hacktoberfest 2022.

As always, humans are humans - and not robots. This means that it's sometimes possible for these pull requests (PRs) to slip through DigitalOcean's reviews and have your pull requests (PRs) counted towards your contributions for Hacktoberfest 2022.

Please be aware that if you made multiple repositories which were all excluded - it's better to be **_safe_** than sorry to say that it's always possible for DigitalOcean to blacklist your GitHub / GitLab account where any pull request (PR) made by other contributors to your repositories will not have their contributions counted towards Hacktoberfest 2022.

DigitalOcean is always looking to implement more safeguarding measures to prevent unfair advantage towards other people and every October in each year, those rules tend to expand.

**Pull request merged**
