### PR TITLE
adding a binary search cpp program

### PR DESCRIPTION
**Pull request by shivani7n7**
#4 adding a cpp program to implement binary search recursively.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
@shivani7n7 As you may see directly from the issue board that @Akshat05-tech were assigned to that particular issue. 
So it is not a good practice to open PRs for the issues that are assigned to others. 
Despite that, we admire your enthusiasm and working spirit. You may create and claim other issues if interested and open the PRs corresponding to them : )

Closing

**Comment by shivani7n7** [comment]
Hey Ayush,
I'm a beginner and I didn't know about this. Really Sorry.
Also, what you suggesting me is to delete my pull request against that
issue. Right?
Thank you!

**Comment by s-ayush2903** [comment]
* No worries, 
* The extract of my previous comment was: do not create a pull request for an issue if someone else is already working on it.
* You are welcome to add any of the algorithms here, but please first create an issue and comment there that you wanna work on that particular issue : )
* You may find [this](https://github.com/hacktoberfest2k20/DataStructures-and-Algorithms#datastructures-and-algorithms) a useful read.

**Comment by shivani7n7** [comment]
Great. Will check it out and follow the rules.
I thought every open request is eligible to be worked on.
Sincere apologies.
Regards!

**Comment by s-ayush2903** [comment]
Ah, don't be sorry. We all were naive once.

**Pull request closed without merging**
